{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-chart.componentName" (list . "backend") }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "app-chart.labels" (list . "backend") | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-chart.selectorLabels" (list . "backend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-chart.labels" (list . "backend") | nindent 8 }}
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          {{- with .Values.backend.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.backend.env .Values.backend.keycloak.enabled }}
          env:
            {{- with .Values.backend.env }}
            {{- (tpl (toYaml .) $) | nindent 12 }}
            {{- end }}
            {{- if .Values.backend.keycloak.enabled }}
            - name: KC_ISSUER_URI
              value: {{ .Values.backend.keycloak.issuerUri | quote }}
            - name: KC_CLIENT_ID
              value: {{ .Values.backend.keycloak.clientId | quote }}
            {{- with .Values.backend.keycloak.audience }}
            - name: KC_AUDIENCE
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.backend.keycloak.jwkSetUri }}
            - name: KC_JWK_SET_URI
              value: {{ . | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.backend.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.probes.liveness.enabled }}
          livenessProbe:
            {{- omit .Values.backend.probes.liveness "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.probes.readiness.enabled }}
          readinessProbe:
            {{- omit .Values.backend.probes.readiness "enabled" | toYaml | nindent 12 }}
          {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
