global:
  namespace: app-prod

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: app.company.com
      paths:
        - path: /
          pathType: Prefix
          service:
            component: frontend
            port: 80
  tls:
    - secretName: app-prod-tls
      hosts:
        - app.company.com

backend:
  image:
    repository: ghcr.io/company/app-backend
    tag: prod-latest
  keycloak:
    enabled: true
    baseUrl: https://sso.company.com
    realm: app
    clientId: app-client
    issuerUri: https://sso.company.com/realms/app
    audience: ""
    jwkSetUri: ""
    callbackUrl: https://app.company.com/oauth/callback
  env:
    - name: APP_ENV
      value: prod
  monitoring:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

frontend:
  image:
    repository: ghcr.io/company/app-frontend
    tag: prod-latest
