apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-local
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:example-org/mono-repo.git
      targetRevision: main
      path: ops/helm/app-chart
      helm:
        valueFiles:
          - $values/environments/local/values.yaml
    - repoURL: git@github.com:example-org/config-repo.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app-local
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-des
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:example-org/mono-repo.git
      targetRevision: main
      path: ops/helm/app-chart
      helm:
        valueFiles:
          - $values/environments/des/values.yaml
    - repoURL: git@github.com:example-org/config-repo.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app-des
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-hom
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:example-org/mono-repo.git
      targetRevision: main
      path: ops/helm/app-chart
      helm:
        valueFiles:
          - $values/environments/hom/values.yaml
    - repoURL: git@github.com:example-org/config-repo.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app-hom
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:example-org/mono-repo.git
      targetRevision: main
      path: ops/helm/app-chart
      helm:
        valueFiles:
          - $values/environments/prod/values.yaml
    - repoURL: git@github.com:example-org/config-repo.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
