global:
  namespace: app-local

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: app.local.test
      paths:
        - path: /
          pathType: Prefix
          service:
            component: frontend
            port: 80
  tls: []

backend:
  image:
    repository: ghcr.io/company/app-backend
    tag: local
  keycloak:
    enabled: true
    baseUrl: https://sso.local.test
    realm: app
    clientId: app-client
    issuerUri: https://sso.local.test/realms/app
    audience: ""
    jwkSetUri: ""
    callbackUrl: https://app.local.test/oauth/callback
  env:
    - name: APP_ENV
      value: local

frontend:
  image:
    repository: ghcr.io/company/app-frontend
    tag: local
